"""no unique constraint for did

Revision ID: 59c73ca86782
Revises: a315e2717517
Create Date: 2022-04-06 19:20:38.182960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c73ca86782'
down_revision = 'a315e2717517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_did', table_name='user')
    op.create_index(op.f('ix_user_did'), 'user', ['did'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_did'), table_name='user')
    op.create_index('ix_user_did', 'user', ['did'], unique=False)
    # ### end Alembic commands ###
